### ISSUE TITLE
ha-sap-terraform-deployments fail with newer salt version on 15-SP4

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/salt-shaptools#89]
Running the code with `salt-3004` fail with this:
```
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):           ID: set_cloud_data_in_grains
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):     Function: crm.cloud_grains_present
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):       Result: False
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):      Comment: An exception occurred in this state: Traceback (most recent call last):
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/state.py", line 2195, in call
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   *cdata["args"], **cdata["kwargs"]
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return self.loader.run(run_func, *args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1203, in run
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return callable(*args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1218, in _run_as
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return _func_or_method(*args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1251, in wrapper
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return f(*args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/var/cache/salt/minion/extmods/states/crmshmod.py", line 582, in cloud_grains_present
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   cloud_provider = __salt__['crm.detect_cloud']()
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return self.loader.run(run_func, *args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1203, in run
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return callable(*args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1218, in _run_as
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   return _func_or_method(*args, **kwargs)
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                 File "/var/cache/salt/minion/extmods/modules/crmshmod.py", line 655, in detect_cloud
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):                   if int(__salt__['crm.version'][0]) <= 3:
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):               TypeError: 'LoadedFunc' object does not support indexing
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):      Started: 13:54:40.084126
module.drbd_node.module.drbd_provision.null_resource.provision[0] (remote-exec):     Duration: 107.737 ms
```

This is related to changes introduced with `salt-3003`:
https://salt.tips/whats-new-in-salt-aluminium-release/#loader-contexts

**Comment by yeoldegrove** [comment]
Instead of using the "magic dunder" `__salt__`, one could make use of `__context__`.
https://docs.saltproject.io/en/latest/topics/development/modules/developing.html#salt
https://docs.saltproject.io/en/latest/topics/development/modules/developing.html#context

This is e.g. done already here:
https://github.com/SUSE/salt-shaptools/blob/329993c11971e6583fa19843f0416ea46c7a9d0c/salt/modules/drbdmod.py#L410

A quick patch would be this:
```
default-vmhana01:~ # diff -Naur /srv/salt/_modules/crmshmod.py.org /srv/salt/_modules/crmshmod.py
--- /srv/salt/_modules/crmshmod.py.org	2022-03-31 11:19:18.887211567 +0000
+++ /srv/salt/_modules/crmshmod.py	2022-03-31 14:03:39.991948578 +0000
@@ -64,8 +64,8 @@
             'The crmsh execution module failed to load: the ha-cluster-init'
             ' package is not available.')

-    __salt__['crm.version'] = version
-    __salt__['crm.use_crm'] = use_crm
+    __context__['crm.version'] = version
+    __context__['crm.use_crm'] = use_crm
     return __virtualname__


@@ -699,7 +699,7 @@
     * google-cloud-platform
     * None (as string)(otherwise)
     '''
-    if int(__salt__['crm.version'][0]) <= 3:
+    if int(__context__['crm.version'][0]) <= 3:
         version = 'python'
     else:
         version = 'python3'
```
Other code might most likely has to be adapted, too.
